name: Laravel

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Connecting server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}} # IP address of the server you wish to ssh into
          key: ${{secrets.SSH_KEY}}
          username: ${{ secrets.SSH_USERNAME }} # User of the server you want to ssh
          script: "cd /var/www/html/app && chmod 770 deploy/deployer.sh && ./deploy/deployer.sh"
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          submodules: recursive
